CREATE TABLE "public"."fortunes" (
    "id" serial,
    "message" text,
    PRIMARY KEY ("id")
);

INSERT INTO fortunes ("message") VALUES('A day for firm decisions!!!!!  Or is it?');
INSERT INTO fortunes ("message") VALUES('A few hours grace before the madness begins again.');
INSERT INTO fortunes ("message") VALUES('A gift of a flower will soon be made to you.');
INSERT INTO fortunes ("message") VALUES('A long-forgotten loved one will appear soon. Buy the negatives at any price.');
INSERT INTO fortunes ("message") VALUES('A tall, dark stranger will have more fun than you.');
INSERT INTO fortunes ("message") VALUES('A visit to a fresh place will bring strange work.');
INSERT INTO fortunes ("message") VALUES('A visit to a strange place will bring fresh work.');
INSERT INTO fortunes ("message") VALUES('A vivid and creative mind characterizes you.');
INSERT INTO fortunes ("message") VALUES('Abandon the search for Truth; settle for a good fantasy.');
INSERT INTO fortunes ("message") VALUES('Accent on helpful side of your nature.  Drain the moat.');
INSERT INTO fortunes ("message") VALUES('Advancement in position.');
INSERT INTO fortunes ("message") VALUES('After your lover has gone you will still have PEANUT BUTTER!');
INSERT INTO fortunes ("message") VALUES('Afternoon very favorable for romance.  Try a single person for a change.');
INSERT INTO fortunes ("message") VALUES('Alimony and bribes will engage a large share of your wealth.');
INSERT INTO fortunes ("message") VALUES('All the troubles you have will pass away very quickly.');
INSERT INTO fortunes ("message") VALUES('Among the lucky, you are the chosen one.');
INSERT INTO fortunes ("message") VALUES('An avocado-tone refrigerator would look good on your resume.');
INSERT INTO fortunes ("message") VALUES('An exotic journey in downtown Newark is in your future.');
INSERT INTO fortunes ("message") VALUES('Another good night not to sleep in a eucalyptus tree.');
INSERT INTO fortunes ("message") VALUES('Are you a turtle?');
INSERT INTO fortunes ("message") VALUES('Are you ever going to do the dishes?  Or will you change your major to biology?');
INSERT INTO fortunes ("message") VALUES('Are you making all this up as you go along?');
INSERT INTO fortunes ("message") VALUES('Are you sure the back door is locked?');
INSERT INTO fortunes ("message") VALUES('Artistic ventures highlighted.  Rob a museum.');
INSERT INTO fortunes ("message") VALUES('Avert misunderstanding by calm, poise, and balance.');
INSERT INTO fortunes ("message") VALUES('Avoid gunfire in the bathroom tonight.');
INSERT INTO fortunes ("message") VALUES('Avoid reality at all costs.');
INSERT INTO fortunes ("message") VALUES('Bank error in your favor.  Collect $200.');
INSERT INTO fortunes ("message") VALUES('Be careful!  Is it classified?');
INSERT INTO fortunes ("message") VALUES('Be careful!  UGLY strikes 9 out of 10!');
INSERT INTO fortunes ("message") VALUES('Be cautious in your daily affairs.');
INSERT INTO fortunes ("message") VALUES('Be cheerful while you are alive. 		-- Phathotep, 24th Century B.C.');
INSERT INTO fortunes ("message") VALUES('Be different: conform.');
INSERT INTO fortunes ("message") VALUES('Be free and open and breezy!  Enjoy!  Things wont get any better so get used to it.');
INSERT INTO fortunes ("message") VALUES('Be security conscious -- National defense is at stake.');
INSERT INTO fortunes ("message") VALUES('Beauty and harmony are as necessary to you as the very breath of life.');
INSERT INTO fortunes ("message") VALUES('Best of all is never to have been born.  Second best is to die soon.');
INSERT INTO fortunes ("message") VALUES('Better hope the life-inspector doesnt come around while you have your life in such a mess.');
INSERT INTO fortunes ("message") VALUES('Beware of a dark-haired man with a loud tie.');
INSERT INTO fortunes ("message") VALUES('Beware of a tall black man with one blond shoe.');
INSERT INTO fortunes ("message") VALUES('Beware of a tall blond man with one black shoe.');
INSERT INTO fortunes ("message") VALUES('Beware of Bigfoot!');
INSERT INTO fortunes ("message") VALUES('Beware of low-flying butterflies.');
INSERT INTO fortunes ("message") VALUES('Beware the one behind you.');
INSERT INTO fortunes ("message") VALUES('Blow it out your ear.');
INSERT INTO fortunes ("message") VALUES('Break into jail and claim police brutality.');
INSERT INTO fortunes ("message") VALUES('Bridge ahead.  Pay troll.');
INSERT INTO fortunes ("message") VALUES('Caution: breathing may be hazardous to your health.');
INSERT INTO fortunes ("message") VALUES('Caution: Keep out of reach of children.');
INSERT INTO fortunes ("message") VALUES('Celebrate Hannibal Day this year.  Take an elephant to lunch.');
INSERT INTO fortunes ("message") VALUES('Change your thoughts and you change your world.');
INSERT INTO fortunes ("message") VALUES('Cheer Up!  Things are getting worse at a slower rate.');
INSERT INTO fortunes ("message") VALUES('Chess tonight.');
INSERT INTO fortunes ("message") VALUES('Chicken Little only has to be right once.');
INSERT INTO fortunes ("message") VALUES('Chicken Little was right.');
INSERT INTO fortunes ("message") VALUES('Cold hands, no gloves.');
INSERT INTO fortunes ("message") VALUES('Communicate!  It cant make things any worse.');
INSERT INTO fortunes ("message") VALUES('Courage is your greatest present need.');
INSERT INTO fortunes ("message") VALUES('Day of inquiry.  You will be subpoenaed.');
INSERT INTO fortunes ("message") VALUES('Do not overtax your powers.');
INSERT INTO fortunes ("message") VALUES('Do not sleep in a eucalyptus tree tonight.');
INSERT INTO fortunes ("message") VALUES('Do nothing unless you must, and when you must act -- hesitate.');
INSERT INTO fortunes ("message") VALUES('Do something unusual today.  Pay a bill.');
INSERT INTO fortunes ("message") VALUES('Do what comes naturally.  Seethe and fume and throw a tantrum.');
INSERT INTO fortunes ("message") VALUES('Domestic happiness and faithful friends.');
INSERT INTO fortunes ("message") VALUES('Dont feed the bats tonight.');
INSERT INTO fortunes ("message") VALUES('Dont get stuck in a closet -- wear yourself out.');
INSERT INTO fortunes ("message") VALUES('Dont get to bragging.');
INSERT INTO fortunes ("message") VALUES('Dont go surfing in South Dakota for a while.');
INSERT INTO fortunes ("message") VALUES('Dont hate yourself in the morning -- sleep till noon.');
INSERT INTO fortunes ("message") VALUES('Dont kiss an elephant on the lips today.');
INSERT INTO fortunes ("message") VALUES('Dont let your mind wander -- its too little to be let out alone.');
INSERT INTO fortunes ("message") VALUES('Dont look back, the lemmings are gaining on you.');
INSERT INTO fortunes ("message") VALUES('Dont look now, but the man in the moon is laughing at you.');
INSERT INTO fortunes ("message") VALUES('Dont look now, but there is a multi-legged creature on your shoulder.');
INSERT INTO fortunes ("message") VALUES('Dont plan any hasty moves.  Youll be evicted soon anyway.');
INSERT INTO fortunes ("message") VALUES('Dont read any sky-writing for the next two weeks.');
INSERT INTO fortunes ("message") VALUES('Dont read everything you believe.');
INSERT INTO fortunes ("message") VALUES('Dont relax!  Its only your tension thats holding you together.');
INSERT INTO fortunes ("message") VALUES('Dont tell any big lies today.  Small ones can be just as effective.');
INSERT INTO fortunes ("message") VALUES('Dont worry so loud, your roommate cant think.');
INSERT INTO fortunes ("message") VALUES('Dont Worry, Be Happy. 		-- Meher Baba');
INSERT INTO fortunes ("message") VALUES('Dont worry.  Lifes too long. 		-- Vincent Sardi, Jr.');
INSERT INTO fortunes ("message") VALUES('Dont you feel more like you do now than you did when you came in?');
INSERT INTO fortunes ("message") VALUES('Dont you wish you had more energy... or less ambition?');
INSERT INTO fortunes ("message") VALUES('Everything that you know is wrong, but you can be straightened out.');
INSERT INTO fortunes ("message") VALUES('Everything will be just tickety-boo today.');
INSERT INTO fortunes ("message") VALUES('Excellent day for putting Slinkies on an escalator.');
INSERT INTO fortunes ("message") VALUES('Excellent day to have a rotten day.');
INSERT INTO fortunes ("message") VALUES('Excellent time to become a missing person.');
INSERT INTO fortunes ("message") VALUES('Executive ability is prominent in your make-up.');
INSERT INTO fortunes ("message") VALUES('Exercise caution in your daily affairs.');
INSERT INTO fortunes ("message") VALUES('Expect a letter from a friend who will ask a favor of you.');
INSERT INTO fortunes ("message") VALUES('Expect the worst, its the least you can do.');
INSERT INTO fortunes ("message") VALUES('Fine day for friends. So-so day for you.');
INSERT INTO fortunes ("message") VALUES('Fine day to work off excess energy.  Steal something heavy.');
INSERT INTO fortunes ("message") VALUES('Fortune: You will be attacked next Wednesday at 3:15 p.m. by six samurai sword wielding purple fish glued to Harley-Davidson motorcycles. Oh, and have a nice day! 		-- Bryce Nesbitt 84');
INSERT INTO fortunes ("message") VALUES('Future looks spotty.  You will spill soup in late evening.');
INSERT INTO fortunes ("message") VALUES('Generosity and perfection are your everlasting goals.');
INSERT INTO fortunes ("message") VALUES('Give him an evasive answer.');
INSERT INTO fortunes ("message") VALUES('Give thought to your reputation.  Consider changing name and moving to a new town.');
INSERT INTO fortunes ("message") VALUES('Give your very best today.  Heaven knows its little enough.');
INSERT INTO fortunes ("message") VALUES('Go to a movie tonight.  Darkness becomes you.');
INSERT INTO fortunes ("message") VALUES('Good day for a change of scene.  Repaper the bedroom wall.');
INSERT INTO fortunes ("message") VALUES('Good day for overcoming obstacles.  Try a steeplechase.');
INSERT INTO fortunes ("message") VALUES('Good day to deal with people in high places; particularly lonely stewardesses.');
INSERT INTO fortunes ("message") VALUES('Good day to let down old friends who need help.');
INSERT INTO fortunes ("message") VALUES('Good news from afar can bring you a welcome visitor.');
INSERT INTO fortunes ("message") VALUES('Good news.  Ten weeks from Friday will be a pretty good day.');
INSERT INTO fortunes ("message") VALUES('Good night to spend with family, but avoid arguments with your mates new lover.');
INSERT INTO fortunes ("message") VALUES('Green light in A.M. for new projects.  Red light in P.M. for traffic tickets.');
INSERT INTO fortunes ("message") VALUES('Hope that the day after you die is a nice day.');
INSERT INTO fortunes ("message") VALUES('If you can read this, youre too close.');
INSERT INTO fortunes ("message") VALUES('If you learn one useless thing every day, in a single year youll learn 365 useless things.');
INSERT INTO fortunes ("message") VALUES('If you sow your wild oats, hope for a crop failure.');
INSERT INTO fortunes ("message") VALUES('If you stand on your head, you will get footprints in your hair.');
INSERT INTO fortunes ("message") VALUES('If you think last Tuesday was a drag, wait till you see what happens tomorrow!');
INSERT INTO fortunes ("message") VALUES('If your life was a horse, youd have to shoot it.');
INSERT INTO fortunes ("message") VALUES('In the stairway of life, youd best take the elevator.');
INSERT INTO fortunes ("message") VALUES('Increased knowledge will help you now.  Have mates phone bugged.');
INSERT INTO fortunes ("message") VALUES('Is that really YOU that is reading this?');
INSERT INTO fortunes ("message") VALUES('Is this really happening?');
INSERT INTO fortunes ("message") VALUES('It is so very hard to be an  on-your-own-take-care-of-yourself-because-there-is-no-one-else-to-do-it-for-you grown-up.');
INSERT INTO fortunes ("message") VALUES('It may or may not be worthwhile, but it still has to be done.');
INSERT INTO fortunes ("message") VALUES('It was all so different before everything changed.');
INSERT INTO fortunes ("message") VALUES('Its a very *__UN*lucky week in which to be took dead. 		-- Churchy La Femme');
INSERT INTO fortunes ("message") VALUES('Its all in the mind, ya know.');
INSERT INTO fortunes ("message") VALUES('Its lucky youre going so slowly, because youre going in the wrong direction.');
INSERT INTO fortunes ("message") VALUES('Just because the message may never be received does not mean it is not worth sending.');
INSERT INTO fortunes ("message") VALUES('Just to have it is enough.');
INSERT INTO fortunes ("message") VALUES('Keep emotionally active.  Cater to your favorite neurosis.');
INSERT INTO fortunes ("message") VALUES('Keep it short for pithy sake.');
INSERT INTO fortunes ("message") VALUES('Lady Luck brings added income today.  Lady friend takes it away tonight.');
INSERT INTO fortunes ("message") VALUES('Learn to pause -- or nothing worthwhile can catch up to you.');
INSERT INTO fortunes ("message") VALUES('Let me put it this way: today is going to be a learning experience.');
INSERT INTO fortunes ("message") VALUES('Life is to you a dashing and bold adventure.');
INSERT INTO fortunes ("message") VALUES('Life, loathe it or ignore it, you cant like it. 		-- Marvin, Hitchhikers Guide to the Galaxy');
INSERT INTO fortunes ("message") VALUES('Live in a world of your own, but always welcome visitors.');
INSERT INTO fortunes ("message") VALUES('Living your life is a task so difficult, it has never been attempted before.');
INSERT INTO fortunes ("message") VALUES('Long life is in store for you.');
INSERT INTO fortunes ("message") VALUES('Look afar and see the end from the beginning.');
INSERT INTO fortunes ("message") VALUES('Love is in the offing.  Be affectionate to one who adores you.');
INSERT INTO fortunes ("message") VALUES('Make a wish, it might come true.');
INSERT INTO fortunes ("message") VALUES('Many changes of mind and mood; do not hesitate too long.');
INSERT INTO fortunes ("message") VALUES('Never be led astray onto the path of virtue.');
INSERT INTO fortunes ("message") VALUES('Never commit yourself!  Let someone else commit you.');
INSERT INTO fortunes ("message") VALUES('Never give an inch!');
INSERT INTO fortunes ("message") VALUES('Never look up when dragons fly overhead.');
INSERT INTO fortunes ("message") VALUES('Never reveal your best argument.');
INSERT INTO fortunes ("message") VALUES('Next Friday will not be your lucky day.  As a matter of fact, you dont have a lucky day this year.');
INSERT INTO fortunes ("message") VALUES('Obviously the only rational solution to your problem is suicide.');
INSERT INTO fortunes ("message") VALUES('Of course you have a purpose -- to find a purpose.');
INSERT INTO fortunes ("message") VALUES('People are beginning to notice you.  Try dressing before you leave the house.');
INSERT INTO fortunes ("message") VALUES('Perfect day for scrubbing the floor and other exciting things.');
INSERT INTO fortunes ("message") VALUES('Questionable day. Ask somebody something.');
INSERT INTO fortunes ("message") VALUES('Reply hazy, ask again later.');
INSERT INTO fortunes ("message") VALUES('Save energy: be apathetic.');
INSERT INTO fortunes ("message") VALUES('Ships are safe in harbor, but they were never meant to stay there.');
INSERT INTO fortunes ("message") VALUES('Slow day.  Practice crawling.');
INSERT INTO fortunes ("message") VALUES('Snow Day -- stay home.');
INSERT INTO fortunes ("message") VALUES('So this it it.  Were going to die.');
INSERT INTO fortunes ("message") VALUES('So youre back... about time...');
INSERT INTO fortunes ("message") VALUES('Someone is speaking well of you.');
INSERT INTO fortunes ("message") VALUES('Someone is speaking well of you. How unusual!');
INSERT INTO fortunes ("message") VALUES('Someone whom you reject today, will reject you tomorrow.');
INSERT INTO fortunes ("message") VALUES('Stay away from flying saucers today.');
INSERT INTO fortunes ("message") VALUES('Stay away from hurricanes for a while.');
INSERT INTO fortunes ("message") VALUES('Stay the curse.');
INSERT INTO fortunes ("message") VALUES('That secret youve been guarding, isnt.');
INSERT INTO fortunes ("message") VALUES('The time is right to make new friends.');
INSERT INTO fortunes ("message") VALUES('The whole world is a tuxedo and you are a pair of brown shoes. 		-- George Gobel');
INSERT INTO fortunes ("message") VALUES('There is a 20');
INSERT INTO fortunes ("message") VALUES('chance of tomorrow.');
INSERT INTO fortunes ("message") VALUES('There is a fly on your nose.');
INSERT INTO fortunes ("message") VALUES('There was a phone call for you.');
INSERT INTO fortunes ("message") VALUES('There will be big changes for you but you will be happy.');
INSERT INTO fortunes ("message") VALUES('Things will be bright in P.M.  A cop will shine a light in your face.');
INSERT INTO fortunes ("message") VALUES('Think twice before speaking, but dont say think think click click.');
INSERT INTO fortunes ("message") VALUES('This life is yours.  Some of it was given to you; the rest, you made yourself.');
INSERT INTO fortunes ("message") VALUES('This will be a memorable month -- no matter how hard you try to forget it.');
INSERT INTO fortunes ("message") VALUES('Time to be aggressive.  Go after a tattooed Virgo.');
INSERT INTO fortunes ("message") VALUES('Today is National Existential Ennui Awareness Day.');
INSERT INTO fortunes ("message") VALUES('Today is the first day of the rest of the mess.');
INSERT INTO fortunes ("message") VALUES('Today is the first day of the rest of your life.');
INSERT INTO fortunes ("message") VALUES('Today is the last day of your life so far.');
INSERT INTO fortunes ("message") VALUES('Today is the tomorrow you worried about yesterday.');
INSERT INTO fortunes ("message") VALUES('Today is what happened to yesterday.');
INSERT INTO fortunes ("message") VALUES('Todays weirdness is tomorrows reason why. 		-- Hunter S. Thompson');
INSERT INTO fortunes ("message") VALUES('Tomorrow will be cancelled due to lack of interest.');
INSERT INTO fortunes ("message") VALUES('Tomorrow, this will be part of the unchangeable past but fortunately, it can still be changed today.');
INSERT INTO fortunes ("message") VALUES('Tomorrow, you can be anywhere.');
INSERT INTO fortunes ("message") VALUES('Tonight you will pay the wages of sin; Dont forget to leave a tip.');
INSERT INTO fortunes ("message") VALUES('Tonights the night: Sleep in a eucalyptus tree.');
INSERT INTO fortunes ("message") VALUES('Troubled day for virgins over 16 who are beautiful and wealthy and live in eucalyptus trees.');
INSERT INTO fortunes ("message") VALUES('Truth will out this morning.  (Which may really mess things up.)');
INSERT INTO fortunes ("message") VALUES('Try the Moo Shu Pork.  It is especially good today.');
INSERT INTO fortunes ("message") VALUES('Try to get all of your posthumous medals in advance.');
INSERT INTO fortunes ("message") VALUES('Try to have as good a life as you can under the circumstances.');
INSERT INTO fortunes ("message") VALUES('Try to relax and enjoy the crisis. 		-- Ashleigh Brilliant');
INSERT INTO fortunes ("message") VALUES('Try to value useful qualities in one who loves you.');
INSERT INTO fortunes ("message") VALUES('Tuesday After Lunch is the cosmic time of the week.');
INSERT INTO fortunes ("message") VALUES('Tuesday is the Wednesday of the rest of your life.');
INSERT INTO fortunes ("message") VALUES('What happened last night can happen again.');
INSERT INTO fortunes ("message") VALUES('While you recently had your problems on the run, theyve regrouped and are making another attack.');
INSERT INTO fortunes ("message") VALUES('Write yourself a threatening letter and pen a defiant reply.');
INSERT INTO fortunes ("message") VALUES('You are a bundle of energy, always on the go.');
INSERT INTO fortunes ("message") VALUES('You are a fluke of the universe; you have no right to be here.');
INSERT INTO fortunes ("message") VALUES('You are a very redundant person, thats what kind of person you are.');
INSERT INTO fortunes ("message") VALUES('You are always busy.');
INSERT INTO fortunes ("message") VALUES('You are as I am with You.');
INSERT INTO fortunes ("message") VALUES('You are capable of planning your future.');
INSERT INTO fortunes ("message") VALUES('You are confused; but this is your normal state.');
INSERT INTO fortunes ("message") VALUES('You are deeply attached to your friends and acquaintances.');
INSERT INTO fortunes ("message") VALUES('You are destined to become the commandant of the fighting men of the department of transportation.');
INSERT INTO fortunes ("message") VALUES('You are dishonest, but never to the point of hurting a friend.');
INSERT INTO fortunes ("message") VALUES('You are fairminded, just and loving.');
INSERT INTO fortunes ("message") VALUES('You are farsighted, a good planner, an ardent lover, and a faithful friend.');
INSERT INTO fortunes ("message") VALUES('You are fighting for survival in your own sweet and gentle way.');
INSERT INTO fortunes ("message") VALUES('You are going to have a new love affair.');
INSERT INTO fortunes ("message") VALUES('You are magnetic in your bearing.');
INSERT INTO fortunes ("message") VALUES('You are not dead yet.  But watch for further reports.');
INSERT INTO fortunes ("message") VALUES('You are number 6!  Who is number one?');
INSERT INTO fortunes ("message") VALUES('You are only young once, but you can stay immature indefinitely.');
INSERT INTO fortunes ("message") VALUES('You are scrupulously honest, frank, and straightforward.  Therefore you have few friends.');
INSERT INTO fortunes ("message") VALUES('You are sick, twisted and perverted.  I like that in a person.');
INSERT INTO fortunes ("message") VALUES('You are so boring that when I see you my feet go to sleep.');
INSERT INTO fortunes ("message") VALUES('You are standing on my toes.');
INSERT INTO fortunes ("message") VALUES('You are taking yourself far too seriously.');
INSERT INTO fortunes ("message") VALUES('You are the only person to ever get this message.');
INSERT INTO fortunes ("message") VALUES('You are wise, witty, and wonderful, but you spend too much time reading this sort of trash.');
INSERT INTO fortunes ("message") VALUES('You attempt things that you do not even plan because of your extreme stupidity.');
INSERT INTO fortunes ("message") VALUES('You can create your own opportunities this week.  Blackmail a senior executive.');
INSERT INTO fortunes ("message") VALUES('You can do very well in speculation where land or anything to do with dirt is concerned.');
INSERT INTO fortunes ("message") VALUES('You can rent this space for only $5 a week.');
INSERT INTO fortunes ("message") VALUES('You could live a better life, if you had a better mind and a better body.');
INSERT INTO fortunes ("message") VALUES('You definitely intend to start living sometime soon.');
INSERT INTO fortunes ("message") VALUES('You dialed 5483.');
INSERT INTO fortunes ("message") VALUES('You display the wonderful traits of charm and courtesy.');
INSERT INTO fortunes ("message") VALUES('You dont become a failure until youre satisfied with being one.');
INSERT INTO fortunes ("message") VALUES('You enjoy the company of other people.');
INSERT INTO fortunes ("message") VALUES('You feel a whole lot more like you do now than you did when you used to.');
INSERT INTO fortunes ("message") VALUES('You fill a much-needed gap.');
INSERT INTO fortunes ("message") VALUES('You get along very well with everyone except animals and people.');
INSERT INTO fortunes ("message") VALUES('You had some happiness once, but your parents moved away, and you had to leave it behind.');
INSERT INTO fortunes ("message") VALUES('You have a deep appreciation of the arts and music.');
INSERT INTO fortunes ("message") VALUES('You have a deep interest in all that is artistic.');
INSERT INTO fortunes ("message") VALUES('You have a reputation for being thoroughly reliable and trustworthy.  A pity that its totally undeserved.');
INSERT INTO fortunes ("message") VALUES('You have a strong appeal for members of the opposite sex.');
INSERT INTO fortunes ("message") VALUES('You have a strong appeal for members of your own sex.');
INSERT INTO fortunes ("message") VALUES('You have a strong desire for a home and your family interests come first.');
INSERT INTO fortunes ("message") VALUES('You have a truly strong individuality.');
INSERT INTO fortunes ("message") VALUES('You have a will that can be influenced by all with whom you come in contact.');
INSERT INTO fortunes ("message") VALUES('You have an ability to sense and know higher truth.');
INSERT INTO fortunes ("message") VALUES('You have an ambitious nature and may make a name for yourself.');
INSERT INTO fortunes ("message") VALUES('You have an unusual equipment for success.  Be sure to use it properly.');
INSERT INTO fortunes ("message") VALUES('You have an unusual magnetic personality.  Dont walk too close to metal objects which are not fastened down.');
INSERT INTO fortunes ("message") VALUES('You have an unusual understanding of the problems of human relationships.');
INSERT INTO fortunes ("message") VALUES('You have been selected for a secret mission.');
INSERT INTO fortunes ("message") VALUES('You have Egyptian flu: youre going to be a mummy.');
INSERT INTO fortunes ("message") VALUES('You have had a long-term stimulation relative to business.');
INSERT INTO fortunes ("message") VALUES('You have literary talent that you should take pains to develop.');
INSERT INTO fortunes ("message") VALUES('You have many friends and very few living enemies.');
INSERT INTO fortunes ("message") VALUES('You have no real enemies.');
INSERT INTO fortunes ("message") VALUES('You have taken yourself too seriously.');
INSERT INTO fortunes ("message") VALUES('You have the body of a 19 year old.  Please return it before it gets wrinkled.');
INSERT INTO fortunes ("message") VALUES('You have the capacity to learn from mistakes.  Youll learn a lot today.');
INSERT INTO fortunes ("message") VALUES('You have the power to influence all with whom you come in contact.');
INSERT INTO fortunes ("message") VALUES('You learn to write as if to someone else because NEXT YEAR YOU WILL BE SOMEONE ELSE.');
INSERT INTO fortunes ("message") VALUES('You like to form new friendships and make new acquaintances.');
INSERT INTO fortunes ("message") VALUES('You look like a million dollars.  All green and wrinkled.');
INSERT INTO fortunes ("message") VALUES('You look tired.');
INSERT INTO fortunes ("message") VALUES('You love peace.');
INSERT INTO fortunes ("message") VALUES('You love your home and want it to be beautiful.');
INSERT INTO fortunes ("message") VALUES('You may be gone tomorrow, but that doesnt mean that you werent here today.');
INSERT INTO fortunes ("message") VALUES('You may be infinitely smaller than some things, but youre infinitely  larger than others.');
INSERT INTO fortunes ("message") VALUES('You may be recognized soon.  Hide.');
INSERT INTO fortunes ("message") VALUES('You may get an opportunity for advancement today.  Watch it!');
INSERT INTO fortunes ("message") VALUES('You may worry about your hair-do today, but tomorrow much peanut butter will be sold.');
INSERT INTO fortunes ("message") VALUES('You need more time; and you probably always will.');
INSERT INTO fortunes ("message") VALUES('You need no longer worry about the future.  This time tomorrow youll be dead.');
INSERT INTO fortunes ("message") VALUES('You never hesitate to tackle the most difficult problems.');
INSERT INTO fortunes ("message") VALUES('You never know how many friends you have until you rent a house on the beach.');
INSERT INTO fortunes ("message") VALUES('You now have Asian Flu.');
INSERT INTO fortunes ("message") VALUES('You own a dog, but you can only feed a cat.');
INSERT INTO fortunes ("message") VALUES('You plan things that you do not even attempt because of your extreme caution.');
INSERT INTO fortunes ("message") VALUES('You possess a mind not merely twisted, but actually sprained.');
INSERT INTO fortunes ("message") VALUES('You prefer the company of the opposite sex, but are well liked by your own.');
INSERT INTO fortunes ("message") VALUES('You recoil from the crude; you tend naturally toward the exquisite.');
INSERT INTO fortunes ("message") VALUES('You seek to shield those you love and you like the role of the provider.');
INSERT INTO fortunes ("message") VALUES('You shall be rewarded for a dastardly deed.');
INSERT INTO fortunes ("message") VALUES('You should emulate your heros, but dont carry it too far.  Especially if they are dead.');
INSERT INTO fortunes ("message") VALUES('You should go home.');
INSERT INTO fortunes ("message") VALUES('You single-handedly fought your way into this hopeless mess.');
INSERT INTO fortunes ("message") VALUES('You teach best what you most need to learn.');
INSERT INTO fortunes ("message") VALUES('You too can wear a nose mitten.');
INSERT INTO fortunes ("message") VALUES('You two ought to be more careful--your love could drag on for years and years.');
INSERT INTO fortunes ("message") VALUES('You will always get the greatest recognition for the job you least like.');
INSERT INTO fortunes ("message") VALUES('You will always have good luck in your personal affairs.');
INSERT INTO fortunes ("message") VALUES('You will attract cultured and artistic people to your home.');
INSERT INTO fortunes ("message") VALUES('You will be a winner today.  Pick a fight with a four-year-old.');
INSERT INTO fortunes ("message") VALUES('You will be advanced socially, without any special effort on your part.');
INSERT INTO fortunes ("message") VALUES('You will be aided greatly by a person whom you thought to be unimportant.');
INSERT INTO fortunes ("message") VALUES('You will be attacked by a beast who has the body of a wolf, the tail of a lion, and the face of Donald Duck.');
INSERT INTO fortunes ("message") VALUES('You will be audited by the Internal Revenue Service.');
INSERT INTO fortunes ("message") VALUES('You will be awarded a medal for disregarding safety in saving someone.');
INSERT INTO fortunes ("message") VALUES('You will be awarded some great honor.');
INSERT INTO fortunes ("message") VALUES('You will be awarded the Nobel Peace Prize... posthumously.');
INSERT INTO fortunes ("message") VALUES('You will be called upon to help a friend in trouble.');
INSERT INTO fortunes ("message") VALUES('You will be dead within a year.');
INSERT INTO fortunes ("message") VALUES('You will be divorced within a year.');
INSERT INTO fortunes ("message") VALUES('You will be given a post of trust and responsibility.');
INSERT INTO fortunes ("message") VALUES('You will be held hostage by a radical group.');
INSERT INTO fortunes ("message") VALUES('You will be honored for contributing your time and skill to a worthy cause.');
INSERT INTO fortunes ("message") VALUES('You will be imprisoned for contributing your time and skill to a bank robbery.');
INSERT INTO fortunes ("message") VALUES('You will be married within a year, and divorced within two.');
INSERT INTO fortunes ("message") VALUES('You will be married within a year.');
INSERT INTO fortunes ("message") VALUES('You will be misunderstood by everyone.');
INSERT INTO fortunes ("message") VALUES('You will be recognized and honored as a community leader.');
INSERT INTO fortunes ("message") VALUES('You will be reincarnated as a toad; and you will be much happier.');
INSERT INTO fortunes ("message") VALUES('You will be run over by a beer truck.');
INSERT INTO fortunes ("message") VALUES('You will be run over by a bus.');
INSERT INTO fortunes ("message") VALUES('You will be singled out for promotion in your work.');
INSERT INTO fortunes ("message") VALUES('You will be successful in love.');
INSERT INTO fortunes ("message") VALUES('You will be surprised by a loud noise.');
INSERT INTO fortunes ("message") VALUES('You will be surrounded by luxury.');
INSERT INTO fortunes ("message") VALUES('You will be the last person to buy a Chrysler.');
INSERT INTO fortunes ("message") VALUES('You will be the victim of a bizarre joke.');
INSERT INTO fortunes ("message") VALUES('You will be Told about it Tomorrow.  Go Home and Prepare Thyself.');
INSERT INTO fortunes ("message") VALUES('You will be traveling and coming into a fortune.');
INSERT INTO fortunes ("message") VALUES('You will be winged by an anti-aircraft battery.');
INSERT INTO fortunes ("message") VALUES('You will become rich and famous unless you dont.');
INSERT INTO fortunes ("message") VALUES('You will contract a rare disease.');
INSERT INTO fortunes ("message") VALUES('You will engage in a profitable business activity.');
INSERT INTO fortunes ("message") VALUES('You will experience a strong urge to do good; but it will pass.');
INSERT INTO fortunes ("message") VALUES('You will feel hungry again in another hour.');
INSERT INTO fortunes ("message") VALUES('You will forget that you ever knew me.');
INSERT INTO fortunes ("message") VALUES('You will gain money by a fattening action.');
INSERT INTO fortunes ("message") VALUES('You will gain money by a speculation or lottery.');
INSERT INTO fortunes ("message") VALUES('You will gain money by an illegal action.');
INSERT INTO fortunes ("message") VALUES('You will gain money by an immoral action.');
INSERT INTO fortunes ("message") VALUES('You will get what you deserve.');
INSERT INTO fortunes ("message") VALUES('You will give someone a piece of your mind, which you can ill afford.');
INSERT INTO fortunes ("message") VALUES('You will have a long and boring life.');
INSERT INTO fortunes ("message") VALUES('You will have a long and unpleasant discussion with your supervisor.');
INSERT INTO fortunes ("message") VALUES('You will have domestic happiness and faithful friends.');
INSERT INTO fortunes ("message") VALUES('You will have good luck and overcome many hardships.');
INSERT INTO fortunes ("message") VALUES('You will have long and healthy life.');
INSERT INTO fortunes ("message") VALUES('You will hear good news from one you thought unfriendly to you.');
INSERT INTO fortunes ("message") VALUES('You will inherit millions of dollars.');
INSERT INTO fortunes ("message") VALUES('You will inherit some money or a small piece of land.');
INSERT INTO fortunes ("message") VALUES('You will live a long, healthy, happy life and make bags of money.');
INSERT INTO fortunes ("message") VALUES('You will live to see your grandchildren.');
INSERT INTO fortunes ("message") VALUES('You will lose your present job and have to become a door to door mayonnaise salesman.');
INSERT INTO fortunes ("message") VALUES('You will meet an important person who will help you advance professionally.');
INSERT INTO fortunes ("message") VALUES('You will never know hunger.');
INSERT INTO fortunes ("message") VALUES('You will not be elected to public office this year.');
INSERT INTO fortunes ("message") VALUES('You will obey or molten silver will be poured into your ears.');
INSERT INTO fortunes ("message") VALUES('You will outgrow your usefulness.');
INSERT INTO fortunes ("message") VALUES('You will overcome the attacks of jealous associates.');
INSERT INTO fortunes ("message") VALUES('You will pass away very quickly.');
INSERT INTO fortunes ("message") VALUES('You will pay for your sins.  If you have already paid, please disregard this message.');
INSERT INTO fortunes ("message") VALUES('You will pioneer the first Martian colony.');
INSERT INTO fortunes ("message") VALUES('You will probably marry after a very brief courtship.');
INSERT INTO fortunes ("message") VALUES('You will reach the highest possible point in your business or profession.');
INSERT INTO fortunes ("message") VALUES('You will receive a legacy which will place you above want.');
INSERT INTO fortunes ("message") VALUES('You will remember something that you should not have forgotten.');
INSERT INTO fortunes ("message") VALUES('You will soon forget this.');
INSERT INTO fortunes ("message") VALUES('You will soon meet a person who will play an important role in your life.');
INSERT INTO fortunes ("message") VALUES('You will step on the night soil of many countries.');
INSERT INTO fortunes ("message") VALUES('You will stop at nothing to reach your objective, but only because your brakes are defective.');
INSERT INTO fortunes ("message") VALUES('You will triumph over your enemy.');
INSERT INTO fortunes ("message") VALUES('You will visit the Dung Pits of Glive soon.');
INSERT INTO fortunes ("message") VALUES('You will win success in whatever calling you adopt.');
INSERT INTO fortunes ("message") VALUES('You will wish you hadnt.');
INSERT INTO fortunes ("message") VALUES('You work very hard.  Dont try to think as well.');
INSERT INTO fortunes ("message") VALUES('You worry too much about your job.  Stop it.  You are not paid enough to worry.');
INSERT INTO fortunes ("message") VALUES('You would if you could but you cant so you wont.');
INSERT INTO fortunes ("message") VALUES('Youd like to do it instantaneously, but thats too slow.');
INSERT INTO fortunes ("message") VALUES('Youll be called to a post requiring ability in handling groups of people.');
INSERT INTO fortunes ("message") VALUES('Youll be sorry...');
INSERT INTO fortunes ("message") VALUES('Youll feel devilish tonight.  Toss dynamite caps under a flamenco dancers heel.');
INSERT INTO fortunes ("message") VALUES('Youll feel much better once youve given up hope.');
INSERT INTO fortunes ("message") VALUES('Youll never be the man your mother was!');
INSERT INTO fortunes ("message") VALUES('Youll never see all the places, or read all the books, but fortunately, theyre not all recommended.');
INSERT INTO fortunes ("message") VALUES('Youll wish that you had done some of the hard things when they were easier to do.');
INSERT INTO fortunes ("message") VALUES('Youre a card which will have to be dealt with.');
INSERT INTO fortunes ("message") VALUES('Youre almost as happy as you think you are.');
INSERT INTO fortunes ("message") VALUES('Youre at the end of the road again.');
INSERT INTO fortunes ("message") VALUES('Youre being followed.  Cut out the hanky-panky for a few days.');
INSERT INTO fortunes ("message") VALUES('Youre currently going through a difficult transition period called Life.');
INSERT INTO fortunes ("message") VALUES('Youre definitely on their list.  The question to ask next is what list it is.');
INSERT INTO fortunes ("message") VALUES('Youre growing out of some of your problems, but there are others that youre growing into.');
INSERT INTO fortunes ("message") VALUES('Youre not my type.  For that matter, youre not even my species!!!');
INSERT INTO fortunes ("message") VALUES('Youre ugly and your mother dresses you funny.');
INSERT INTO fortunes ("message") VALUES('Youre working under a slight handicap.  You happen to be human.');
INSERT INTO fortunes ("message") VALUES('Youve been leading a dogs life.  Stay off the furniture.');
INSERT INTO fortunes ("message") VALUES('Your aim is high and to the right.');
INSERT INTO fortunes ("message") VALUES('Your aims are high, and you are capable of much.');
INSERT INTO fortunes ("message") VALUES('Your analyst has you mixed up with another patient.  Dont believe a thing he tells you.');
INSERT INTO fortunes ("message") VALUES('Your best consolation is the hope that the things you failed to get werent really worth having.');
INSERT INTO fortunes ("message") VALUES('Your boss climbed the corporate ladder, wrong by wrong.');
INSERT INTO fortunes ("message") VALUES('Your boss is a few sandwiches short of a picnic.');
INSERT INTO fortunes ("message") VALUES('Your boyfriend takes chocolate from strangers.');
INSERT INTO fortunes ("message") VALUES('Your business will assume vast proportions.');
INSERT INTO fortunes ("message") VALUES('Your business will go through a period of considerable expansion.');
INSERT INTO fortunes ("message") VALUES('Your depth of comprehension may tend to make you lax in worldly ways.');
INSERT INTO fortunes ("message") VALUES('Your domestic life may be harmonious.');
INSERT INTO fortunes ("message") VALUES('Your fly might be open (but dont check it just now).');
INSERT INTO fortunes ("message") VALUES('Your goose is cooked. (Your current chick is burned up too!)');
INSERT INTO fortunes ("message") VALUES('Your heart is pure, and your mind clear, and your soul devout.');
INSERT INTO fortunes ("message") VALUES('Your ignorance cramps my conversation.');
INSERT INTO fortunes ("message") VALUES('Your life would be very empty if you had nothing to regret.');
INSERT INTO fortunes ("message") VALUES('Your love life will be happy and harmonious.');
INSERT INTO fortunes ("message") VALUES('Your love life will be... interesting.');
INSERT INTO fortunes ("message") VALUES('Your lover will never wish to leave you.');
INSERT INTO fortunes ("message") VALUES('Your lucky color has faded.');
INSERT INTO fortunes ("message") VALUES('Your lucky number has been disconnected.');
INSERT INTO fortunes ("message") VALUES('Your lucky number is 3552664958674928.  Watch for it everywhere.');
INSERT INTO fortunes ("message") VALUES('Your mode of life will be changed for the better because of good news soon.');
INSERT INTO fortunes ("message") VALUES('Your mode of life will be changed for the better because of new developments.');
INSERT INTO fortunes ("message") VALUES('Your motives for doing whatever good deed you may have in mind will be misinterpreted by somebody.');
INSERT INTO fortunes ("message") VALUES('Your nature demands love and your happiness depends on it.');
INSERT INTO fortunes ("message") VALUES('Your object is to save the world, while still leading a pleasant life.');
INSERT INTO fortunes ("message") VALUES('Your own qualities will help prevent your advancement in the world.');
INSERT INTO fortunes ("message") VALUES('Your present plans will be successful.');
INSERT INTO fortunes ("message") VALUES('Your reasoning is excellent -- its only your basic assumptions that are wrong.');
INSERT INTO fortunes ("message") VALUES('Your reasoning powers are good, and you are a fairly good planner.');
INSERT INTO fortunes ("message") VALUES('Your sister swims out to meet troop ships.');
INSERT INTO fortunes ("message") VALUES('Your society will be sought by people of taste and refinement.');
INSERT INTO fortunes ("message") VALUES('Your step will soil many countries.');
INSERT INTO fortunes ("message") VALUES('Your supervisor is thinking about you.');
INSERT INTO fortunes ("message") VALUES('Your talents will be recognized and suitably rewarded.');
INSERT INTO fortunes ("message") VALUES('Your temporary financial embarrassment will be relieved in a surprising manner.');
INSERT INTO fortunes ("message") VALUES('Your true value depends entirely on what you are compared with.');