[package]
name = "app"
version = "0.0.1"
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-rt = "0.2.5"
actix-web = "1.0.7"
actix-http = "0.2.9"
actix-server = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1.29"
tokio-postgres = "0.4.0-rc.3"

