[package]
name = "app"
version = "0.1.0"
edition = "2018"

[dependencies]
nickel = "0.11"
postgres = "0.16.0-rc.1"
r2d2_postgres = "0.15.0-rc.1"
r2d2 = "0.8.5"
serde = "1.0"
serde_json = "1.0"
serde_postgres = "0.1.3"
serde_derive = "1.0"
