version: "3"
services:
  api:
    depends_on: [db]
    build: "${ROOT}/configurations/${CONFIGURATION}"
    environment:
      RUST_BACKTRACE: 1
    ports:
      - 3000:3000
  db:
    build: "${ROOT}/database"
    environment:
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080