version: "3"
services:
  api:
    depends_on: [db]
    build: "${ROOT}/configurations/${CONFIGURATION}"
    ports:
      - 3000:3000
    volumes:
      - "${ROOT}/configurations/${CONFIGURATION}:/src"
    environment:
      PGHOST: "${PGHOST}"
      PGPORT: "${PGPORT}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
      PGCONNSTRING: "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}"
  db:
    command: "postgres -N 50000"
    build: "${ROOT}/database"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
