version: "3"
services:
  api:
    build: "${ROOT}/configurations/${CONFIGURATION}"
    ports:
      - 3000:3000
    environment:
      PGHOST: "${PGHOST}"
      PGPORT: "${PGPORT}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
      PGCONNSTRING: "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}"

